[workspace]
members = [
    "primary",
    "secondary",
    "components",
    "configs",
]

resolver = "2"

[patch.crates-io]
bitvec = {git = "https://github.com/alexanderkjall/bitvec.git", branch = "upgrade-radium-to-1"}
