[package]
name = "configs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyberon = {git = "https://github.com/Ben-PH/keyberon"}
transpose = {git = "https://github.com/Ben-PH/transpose"}
