name: check

on:
  pull_request:
    branches:
      - main


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3
      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          ldproxy: false
          buildtargets: esp32s3

      - uses: Swatinem/rust-cache@v2

      - name: check rustfmt
        run: cargo fmt -- --check --color always

      - name: clippy
        run: cargo clippy -- -D warnings

